spring:
  application:
    name: AIHub
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/aihub?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 050815
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      max-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 20050918
langchain4j:
  community:
    dashscope:
      chat-model:
        api-key : ${ALI_API_KEY}
        model-name: qwen-max
      streaming-chat-model:
        api-key: ${ALI_API_KEY}
        model-name: qwq-32b-preview
      embedding-model:
        api-key: ${ALI_API_KEY}
        model-name: text-embedding-v3
  tavily:
    api-key: ${TAVILY_API_KEY}
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

dai:
  framework:
    jwt:
      base64-encoded-secret-key: $2a$10$PVtHnkj86mJgf6li/yron.LRx/cQAlaiZkBJ9BeogCNTryXJRT1YC
      ttl: 3600000

logging:
  level:
    org:
      springframework:
        data:
          neo4j=DEBUG:

aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: ${OSS_ACCESS_KEY_ID}
    accessKeySecret: ${OSS_ACCESS_KEY_SECRET}
    bucketName: aihub-dai